### ISSUE TITLE
Build broken with Scintilla 3.6.6

### ISSUE THREAD

**Issue by eht16** [codebrainz/geanypy#43]
Since the update of Scintilla to 3.6.6 in Geany master, compiling GeanyPy fails.

For build logs, see http://nightly.geany.org/misc/build_gtk224_plugins_stderr.log.

This is because Scintilla 3.6.6 now defines `NotifyHeader` different than before and this conflicts with the `NotifyHeader` type in src/geanypy-scintilla.h.
I guess renaming `NotifyHeader` in GeanyPy to some more distinctive name should resolve this.

**Comment by elextr** [comment]
I had a look at it and as far as I can tell the culprit line

```
#define NotifyHeader Sci_NotifyHeader
```

has been in Scintilla.h for ages, so I'm not sure how geanypy ever used to work, or what we or scintilla changed.

**Comment by codebrainz** [comment]
> has been in Scintilla.h for ages, so I'm not sure how geanypy ever used to work, or what we or scintilla changed.

I guess before, that macro was expanding to `Sci_NotifyHeader`, a valid struct typedef name, like this:

```c
typedef struct {
    PyObject_HEAD
    SCNotification *notif;
} /*begin expansion*/ Sci_NotifyHeader /*end expansion*/;
```

And didn't conflict with Scintilla's definition by that name since it was not typedef'd before [this change](https://sourceforge.net/p/scintilla/code/ci/64d36f2eac4de4fa1a4ef478fe784bd9b522fa3e/), it would've required the `struct` keyword in C to conflict. After that change, there are now two typedefs for `Sci_NotifyHeader`, the one caused by Scintilla's grotesque use of non-namespace-prefixed macros in GeanyPy, and the new one @kugel- added.

It would probably be easiest to rename the typedef in GeanyPy as @eht16 mentioned to avoid conflicting with Scintilla's horrible macro, but it might be worth fixing in Scintilla as well, to get rid of that yucky `#define` or rename it to start with `Sci_` or whatever.

**Comment by elextr** [comment]
Agree its bad karma for Scintilla to make non-namespaced defines, but this is only one of several so I doubt they will get removed, and anyway it would not be backward compatible.

**Comment by codebrainz** [comment]
Yeah probably, though it might be useful for anyone with a SourceForge account to report it to Scintilla so Neil is aware of the trouble it caused. Maybe eventually he would move them to a compatibility header or guard them in some kind of (namespace-prefixed) deprecation macro in a future release.

**Comment by elextr** [comment]
@eht16 I wondered why the archlinux builds were passing, they say they are building 1.26?????

**Comment by eht16** [comment]
Because everything runs better on ArchLinux :).
The real reason is that the ArchLinux nightly builds are disabled. I disabled them because I couldn't find anything in the logs that they were used by any users and so decided to save some IO on the build machine. On a closer look, you'll notice the last build is back in 2015.

**Comment by eht16** [comment]
@codebrainz do you consider https://github.com/codebrainz/geanypy/commit/e0e209f4b0b2f1a03f7080c033bbfdcca01a003d as the final fix? It looks rather like a hack to me.

**Comment by elextr** [comment]
On 3 June 2016 at 03:47, Enrico Tröger <notifications@github.com> wrote:

> Because everything runs better on ArchLinux :).
>

​[end political advertisement] :-D​



> The real reason is that the ArchLinux nightly builds are disabled. I
> disabled them because I couldn't find anything in the logs that they were
> used by any users and so decided to save some IO on the build machine. On a
> closer look, you'll notice the last build is back in 2015.
>

​Sounds fair, did you turn the others off as well? Debian seems to have
missed 2 June?​

**Comment by codebrainz** [comment]
@eht16 it's kind of hacky, but Scintilla having a non-prefixed (redundant) macro is the real issue, and this "fix" ensures that particular bug cannot re-occur in GeanyPy. I'm not opposed to fixing it better. I tried to match the naming of the wrapped types, and renaming it would make it not match (not a huge deal, even an underscore would fix the issue).

**Comment by elextr** [comment]
Yay, all green again :)

**Comment by eht16** [comment]
> ​Sounds fair, did you turn the others off as well? Debian seems to have
> missed 2 June?​
No, only the ArchLinux builds are disabled.
The Debian ones and the others which were missing in the last days were
just failing due to this issue. And since it is now fixed in master, the
builds went green again.
