### ISSUE TITLE
Getting instances of Scintilla

### ISSUE THREAD

**Issue by harryherold** [codebrainz/geanypy#44]
Hi,
want to get an instances of scintilla for getting the current line.
What can i used ?

I looked forsome like this  scintilla_get_current but i found only
geany.scintilla.Scintilla.
Having an instances of this class won't work .

**Comment by b4n** [comment]
`Document.get_current().editor.sci` or something similar.  The C API for this would be
```C
GeanyDocument *doc = document_get_current();
if (doc != NULL) {
    ScintillaObject *sci = doc->editor->sci;
}
```

**Comment by harryherold** [comment]
Yes, I tried this:
```
import geany
doc = geany.document.get_current()
s = doc.editor.sci
Traceback (most recent call last):
File "<input>", line 1, in <module>
AttributeError: 'geany.editor.Editor' object has no attribute 'sci'
```

**Comment by b4n** [comment]
Looking at [the code](https://github.com/codebrainz/geanypy/blob/master/src/geanypy-editor.c#L322) it's called `scintilla`, not abbreviated.

**Comment by b4n** [comment]
`help(doc.editor)` should… help :]

**Comment by harryherold** [comment]
Yeah, it works! Many thanks!
